COPY nginx.conf /etc/nginx/conf.d/default.conf 

COPY --from=builder /app/dist/tpf-frontend /usr/share/nginx/html

# Exponer el puerto por defecto de Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]